<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Jenis extends CI_Controller
{


    function __construct()
    {
        parent::__construct();
        $this->load->model('Jenis_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $jenis = $this->Jenis_model->get_all();

        $data = array(
            'jenis_data' => $jenis,
        );
        $this->template->load('template', 'jenis_list', $data);
    }

    public function read($id)
    {
        $row = $this->Jenis_model->get_by_id($id);
        if ($row) {
            $data = array(
                'id' => $row->id,
                'jenis_inventory' => $row->jenis_inventory,
                'prefix' => $row->prefix,
                'parent' => $row->parent,
            );
            $this->template->load('template', 'jenis_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('jenis'));
        }
    }

    public function create()
    {
        $list_jenis = $this->Jenis_model->get_all();
        $data = array(
            'button' => 'Create',
            'action' => site_url('jenis/create_action'),
            'id' => set_value('id'),
            'jenis_inventory' => set_value('jenis_inventory'),
            'prefix' => set_value('prefix'),
            'parent' => 0,
            'list_jenis' => $list_jenis,
        );
        $this->template->load('template', 'jenis_form', $data);
    }

    public function create_action()
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
                'jenis_inventory' => $this->input->post('jenis_inventory', TRUE),
                'prefix' => $this->input->post('prefix', TRUE),
                'parent' => $this->input->post('parent', TRUE),
            );

            $this->Jenis_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('jenis'));
        }
    }

    public function update($id)
    {
        $row = $this->Jenis_model->get_by_id($id);
        $list_jenis = $this->Jenis_model->get_list_jenis();
        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('jenis/update_action'),
                'id' => set_value('id', $row->id),
                'jenis_inventory' => set_value('jenis_inventory', $row->jenis_inventory),
                'prefix' => set_value('prefix', $row->prefix),
                'parent' => set_value('parent', $row->parent),
                'list_jenis' => $list_jenis,
            );
            $this->template->load('template', 'jenis_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('jenis'));
        }
    }

    public function update_action()
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
                'jenis_inventory' => $this->input->post('jenis_inventory', TRUE),
                'prefix' => $this->input->post('prefix', TRUE),
                'parent' => $this->input->post('parent', TRUE),
            );

            $this->Jenis_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('jenis'));
        }
    }

    public function delete($id)
    {
        $tes = $this->Jenis_model->cek_data($id);

        if ($tes) {
            $this->Jenis_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('jenis'));
        } else {

            redirect(site_url('jenis'));
        }
    }

    public function _rules()
    {
        $this->form_validation->set_rules('jenis_inventory', 'jenis inventory', 'trim|required');
        $this->form_validation->set_rules('prefix', 'prefix', 'trim|required');
        $this->form_validation->set_rules('parent', 'parent', 'trim|required');

        $this->form_validation->set_rules('id', 'id', 'trim');
        $this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }
}

/* End of file Jenis.php */
/* Location: ./application/controllers/Jenis.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2024-02-16 12:37:03 */
/* http://harviacode.com */
