<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Barang_inventory_model extends CI_Model
{

    public $table = 'barang_inventory';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }
    function get_nomor($id_jenis)
    {
        $this->load->model('Jenis_model');
        $jenis = $this->Jenis_model->get_by_id($id_jenis);
        $nomor = $jenis->prefix;
        if ($jenis->parent > 0) {
            $id_parent = $jenis->parent;
            while ($id_parent > 0) {
                $pjenis = $this->Jenis_model->get_by_id($id_parent);
                $nomor =  $pjenis->prefix . '.' . $nomor;
                $id_parent = $pjenis->parent;
            }
        }
        $this->db->where('id_jenis', $id_jenis);
        $this->db->from('barang_inventory');
        $c = $this->db->count_all_results();
        $c = $c + 1;
        return $nomor . '.' . str_pad($c, 3, '0', STR_PAD_LEFT);
    }
    function get_maintenance_schedule()
    {
        $query = 'select barang_inventory.*, maintenance.*, jenis.jenis_inventory, lokasi.ruang, lokasi.nomor_lantai 
        from maintenance
        left join barang_inventory
        on maintenance.id_barang=barang_inventory.id
        left join jenis
        on barang_inventory.id_jenis=jenis.id
        left join lokasi
        on barang_inventory.id_lokasi=lokasi.id
        where maintenance.done =0 
        order by maintenance.next_due_date asc';
        return $this->db->query($query)->result();
    }
    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    function get_detail_barang($id)
    {
        $this->db->select('barang_inventory.*');
        $this->db->select('jenis.jenis_inventory');
        $this->db->select('lokasi.ruang,lokasi.nomor_lantai');
        $this->db->from('barang_inventory');
        $this->db->join('jenis', 'jenis.id=barang_inventory.id_jenis', 'left');
        $this->db->join('lokasi', 'lokasi.id=barang_inventory.id_lokasi', 'left');
        $this->db->where('barang_inventory.id', $id);
        return $this->db->get()->row();
    }
    // get total rows
    function total_rows($q = NULL)
    {

        $this->db->or_like('nomor', $q);
        $this->db->or_like('nama_barang', $q);
        $this->db->or_like('spesifikasi', $q);

        $this->db->from($this->table);
        return $this->db->count_all_results();
    }
    function cek_before_delete($id)
    {
        $this->db->where('id_barang', $id);
        return $this->db->get('maintenance')->result();
    }
    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->select('barang_inventory.*');
        $this->db->select('jenis.jenis_inventory as jenis');
        $this->db->select('lokasi.ruang as lokasi');
        $this->db->from($this->table);
        $this->db->join('jenis', 'jenis.id=barang_inventory.id_jenis', 'left');
        $this->db->join('lokasi', 'lokasi.id=barang_inventory.id_lokasi', 'left');

        $this->db->order_by($this->id, $this->order);

        $this->db->or_like('barang_inventory.nomor', $q);
        $this->db->or_like('barang_inventory.nama_barang', $q);

        $this->db->or_like('barang_inventory.spesifikasi', $q);

        $this->db->limit($limit, $start);
        return $this->db->get()->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file Barang_inventory_model.php */
/* Location: ./application/models/Barang_inventory_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2024-02-18 15:28:38 */
/* http://harviacode.com */
