<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Jenis_model extends CI_Model
{

    public $table = 'jenis';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all($id_induk = 0)
    {
        $jenis = array();
        $this->db->where('parent', $id_induk);
        $result_set = $this->db->get($this->table)->result_array();
        foreach ($result_set as $r) {
            $r['child'] = $this->get_all($r['id']);
            $jenis[] = $r;
        }
        return $jenis;
    }
    function get_list_jenis()
    {
        $data = $this->db->get($this->table)->result();
        return $data;
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    function cek_data($id)
    {
        $this->db->where('id', $id);
        $cek = $this->db->get('jenis')->row();
        if ($cek) {
            $this->db->where('parent', $id);
            $p = $this->db->get('jenis')->row();
            if ($p) {
                $this->session->set_flashdata('message', 'Tidak dapat menghapus data karena terkait dengan data lainnya');
                return false;
            } else {
                $this->db->where('id_jenis', $id);
                $ditabel_brg = $this->db->get('barang_inventory')->row();
                if ($ditabel_brg) {
                    $this->session->set_flashdata('message', 'Tidak dapat menghapus data karena terkait dengan data barang');
                    return false;
                } else {
                    return true;
                }
            }
        } else {
            $this->session->set_flashdata('message', 'Invalid Request');
            return false;
        }
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id', $q);
        $this->db->or_like('jenis_inventory', $q);
        $this->db->or_like('prefix', $q);
        $this->db->or_like('parent', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
        $this->db->or_like('jenis_inventory', $q);
        $this->db->or_like('prefix', $q);
        $this->db->or_like('parent', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file Jenis_model.php */
/* Location: ./application/models/Jenis_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2024-02-16 12:37:03 */
/* http://harviacode.com */
